# SarlakBot v6 Full - Pre-commit Configuration
# Automated code quality checks before commits

repos:
  # Black - Code formatting
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Ruff - Fast linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # MyPy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: requirements-txt-fixer

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-r, app/, -f, json, -o, bandit-report.json]
        exclude: tests/

  # Custom SarlakBot checks
  - repo: local
    hooks:
      - id: sarlakbot-audit
        name: SarlakBot Audit Check
        entry: python scripts/audit_analyzer.py
        language: system
        files: \.py$
        pass_filenames: false

      - id: sarlakbot-tests
        name: SarlakBot Test Suite
        entry: python -m pytest tests/ -v
        language: system
        files: \.py$
        pass_filenames: false

      - id: sarlakbot-docs
        name: SarlakBot Documentation Check
        entry: python -c "import os; assert os.path.exists('DOCUMENTATION.md'), 'Missing DOCUMENTATION.md'"
        language: system
        files: \.py$
        pass_filenames: false

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
