#!/bin/bash

# SarlakBot v6 Full - Complete Server Setup Fix
# This script fixes all server configuration issues

SERVER_IP="91.107.128.14"
SERVER_USER="ali"
SERVER_PASS="ali456456"

echo "🔧 Fixing SarlakBot v6 Full server setup..."

expect << EOF
spawn ssh $SERVER_USER@$SERVER_IP
expect "password:"
send "$SERVER_PASS\r"
expect "$ "
send "cd botsarlak-core\r"
expect "$ "
send "echo '=== STOPPING CURRENT SERVICE ==='\r"
expect "$ "
send "sudo systemctl stop botsarlak-core.service\r"
expect "$ "
send "echo '=== UPDATING SERVICE FILE ==='\r"
expect "$ "
send "sudo cp /tmp/botsarlak-core.service /etc/systemd/system/ 2>/dev/null || echo 'Service file not found'\r"
expect "$ "
send "echo '=== CREATING PROPER SERVICE FILE ==='\r"
expect "$ "
send "sudo tee /etc/systemd/system/botsarlak-core.service > /dev/null << 'EOL'\r"
expect "$ "
send "[Unit]\r"
expect "$ "
send "Description=SarlakBot v6 Full Telegram Bot\r"
expect "$ "
send "After=network.target postgresql.service redis-server.service\r"
expect "$ "
send "Wants=postgresql.service redis-server.service\r"
expect "$ "
send "\r"
expect "$ "
send "[Service]\r"
expect "$ "
send "Type=simple\r"
expect "$ "
send "User=ali\r"
expect "$ "
send "Group=ali\r"
expect "$ "
send "WorkingDirectory=/home/ali/botsarlak-core\r"
expect "$ "
send "Environment=PATH=/usr/bin:/usr/local/bin\r"
expect "$ "
send "Environment=PYTHONPATH=/home/ali/botsarlak-core\r"
expect "$ "
send "ExecStart=/usr/bin/python3 /home/ali/botsarlak-core/main.py\r"
expect "$ "
send "Restart=always\r"
expect "$ "
send "RestartSec=10\r"
expect "$ "
send "StandardOutput=journal\r"
expect "$ "
send "StandardError=journal\r"
expect "$ "
send "\r"
expect "$ "
send "[Install]\r"
expect "$ "
send "WantedBy=multi-user.target\r"
expect "$ "
send "EOL\r"
expect "$ "
send "echo '=== RELOADING SYSTEMD ==='\r"
expect "$ "
send "sudo systemctl daemon-reload\r"
expect "$ "
send "echo '=== ENABLING SERVICE ==='\r"
expect "$ "
send "sudo systemctl enable botsarlak-core.service\r"
expect "$ "
send "echo '=== STARTING SERVICE ==='\r"
expect "$ "
send "sudo systemctl start botsarlak-core.service\r"
expect "$ "
send "echo '=== CHECKING SERVICE STATUS ==='\r"
expect "$ "
send "sudo systemctl status botsarlak-core.service\r"
expect "$ "
send "echo '=== CHECKING PROCESSES ==='\r"
expect "$ "
send "ps aux | grep python | grep -v grep\r"
expect "$ "
send "echo '=== CHECKING LOGS ==='\r"
expect "$ "
send "sudo journalctl -u botsarlak-core.service --no-pager -n 20\r"
expect "$ "
send "exit\r"
interact
EOF

echo "✅ Server setup fix completed!"
