#!/bin/bash

# Setup script for dual bots on server
echo "🤖 Setting up dual bots on server..."

expect << 'EOF'
spawn ssh ali@91.107.128.14
expect "password:"
send "ali456456\r"
expect "$ "
send "cd botsarlak-core\r"
expect "$ "
send "echo '=== CREATING TEST BOT ENV ==='\r"
expect "$ "
send "cat > .env.test << 'ENVEOF'\r"
expect "$ "
send "# Test Bot Configuration\r"
expect "$ "
send "BOT_TOKEN=8028965917:AAFw23S-_894fwa_ioJmtsS47d5l_XGcK7g\r"
expect "$ "
send "BOT_USERNAME=botsarlak_test\r"
expect "$ "
send "BOT_NAME=Sarlak Academy Test Bot\r"
expect "$ "
send "\r"
expect "$ "
send "# Database Configuration\r"
expect "$ "
send "DATABASE_URL=postgresql+asyncpg://botsarlak_user:botsarlak_pass123@localhost/botsarlak_core\r"
expect "$ "
send "DATABASE_HOST=localhost\r"
expect "$ "
send "DATABASE_PORT=5432\r"
expect "$ "
send "DATABASE_NAME=botsarlak_core\r"
expect "$ "
send "DATABASE_USER=botsarlak_user\r"
expect "$ "
send "DATABASE_PASSWORD=botsarlak_pass123\r"
expect "$ "
send "\r"
expect "$ "
send "# Redis Configuration\r"
expect "$ "
send "REDIS_URL=redis://localhost:6379/1\r"
expect "$ "
send "REDIS_HOST=localhost\r"
expect "$ "
send "REDIS_PORT=6379\r"
expect "$ "
send "REDIS_DB=1\r"
expect "$ "
send "\r"
expect "$ "
send "# Environment\r"
expect "$ "
send "ENVIRONMENT=test\r"
expect "$ "
send "DEBUG=true\r"
expect "$ "
send "ENVEOF\r"
expect "$ "
send "echo '=== CREATING MAIN BOT ENV ==='\r"
expect "$ "
send "cat > .env.main << 'ENVEOF'\r"
expect "$ "
send "# Main Bot Configuration\r"
expect "$ "
send "BOT_TOKEN=7214099093:AAEePAXAk8lBGULYzUbQS-6MiwplofDze8o\r"
expect "$ "
send "BOT_USERNAME=botsarlak_core\r"
expect "$ "
send "BOT_NAME=Sarlak Academy Bot\r"
expect "$ "
send "\r"
expect "$ "
send "# Database Configuration\r"
expect "$ "
send "DATABASE_URL=postgresql+asyncpg://botsarlak_user:botsarlak_pass123@localhost/botsarlak_core\r"
expect "$ "
send "DATABASE_HOST=localhost\r"
expect "$ "
send "DATABASE_PORT=5432\r"
expect "$ "
send "DATABASE_NAME=botsarlak_core\r"
expect "$ "
send "DATABASE_USER=botsarlak_user\r"
expect "$ "
send "DATABASE_PASSWORD=botsarlak_pass123\r"
expect "$ "
send "\r"
expect "$ "
send "# Redis Configuration\r"
expect "$ "
send "REDIS_URL=redis://localhost:6379/0\r"
expect "$ "
send "REDIS_HOST=localhost\r"
expect "$ "
send "REDIS_PORT=6379\r"
expect "$ "
send "REDIS_DB=0\r"
expect "$ "
send "\r"
expect "$ "
send "# Environment\r"
expect "$ "
send "ENVIRONMENT=production\r"
expect "$ "
send "DEBUG=false\r"
expect "$ "
send "ENVEOF\r"
expect "$ "
send "echo '=== STARTING TEST BOT ==='\r"
expect "$ "
send "cp .env.test .env\r"
expect "$ "
send "nohup python3 app/bot.py > test_bot.log 2>&1 &\r"
expect "$ "
send "sleep 3\r"
expect "$ "
send "echo '=== STARTING MAIN BOT ==='\r"
expect "$ "
send "cp .env.main .env\r"
expect "$ "
send "nohup python3 app/bot.py > main_bot.log 2>&1 &\r"
expect "$ "
send "sleep 3\r"
expect "$ "
send "echo '=== CHECKING PROCESSES ==='\r"
expect "$ "
send "ps aux | grep python | grep bot\r"
expect "$ "
send "echo '=== CHECKING LOGS ==='\r"
expect "$ "
send "tail -5 test_bot.log\r"
expect "$ "
send "tail -5 main_bot.log\r"
expect "$ "
send "exit\r"
interact
EOF

echo "✅ Dual bot setup completed!"
